/// Flutter icons MyIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcon
///      fonts:
///       - asset: fonts/MyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcon {
  MyIcon._();

  static const _kFontFam = 'MyIcon';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData console = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData family = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData investment = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cosmetics = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyebrow = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hairSalon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lipstick = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData makeUpBag = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData makeup = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nailPolish = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lipstick1 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduationCap = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reading = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colorPalette = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schoolBag = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supplies = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData study = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stationery = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worker = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowling = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popcorn = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joystick = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onlineGaming = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pokerCards = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bycicle = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badminton = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exercise = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muscle = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inflatableBoat = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData net = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weightlifting = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData babyBoy = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData babyBottle = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abcBlock = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData petFood = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cradle = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pawprint = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agreement = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData budget = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData businessAndFinance = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCard = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar1 = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_1 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chickenLeg = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cupcake = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iceCream = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocktail = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icedCoffee = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watermelon = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iftar = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplane = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cruise = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricCar = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gasStation = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData petrolCan = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData takeOff = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train1 = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buyHome = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightBulb = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phoneCall = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recycleBin = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waterBill = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill1 = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maintenance = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dress = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groceryCart = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hanger = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onlineShop = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ring = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingBag = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sneakers = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wristwatch = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCard1 = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dong = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euro = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggyBank2 = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollarSymbol = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purse = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggyBank = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
